# Used to integrate with Microsoft VS Code remote debug feature.
---

services:
  nautobot:
    environment:
      - "PYDEVD_DISABLE_FILE_VALIDATION=1"
      # - "REMOTE_TEST_DEBUG_ENABLE=True"
    ports:
      - "8080:8080"
      - "6899:6899"  # For remote debugging of nautobot
      - "6897:6897"  # For remote debugging of tests
    entrypoint: ""
    command: >
      sh -c "
      pip install debugpy &&
      /docker-entrypoint.sh &&
      python -m debugpy --listen 0.0.0.0:6899 -m nautobot.core.cli runserver 0.0.0.0:8080 --insecure"
  worker:
    environment:
      - "PYDEVD_DISABLE_FILE_VALIDATION=1"
    ports:
      - "6898:6898"  # For remote debugging of Jobs (Celery)
    entrypoint: ""
    command: >
      sh -c "
      pip install debugpy &&
      watchmedo auto-restart --directory './' --pattern '*.py' --recursive -- python -m debugpy --listen 0.0.0.0:6898 -m nautobot.core.cli celery worker -l INFO --events"
